access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
  profiles:
    active: dev
  datasource:
    url: 'jdbc:postgresql://localhost:5432/record_db'
    username: 'record_db'
    password: 'pswd'
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQL81Dialect'
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG
